# Site Settings
title: Chips and Thoughts
author: Abdullah Sahruri
description: Computer Architecture Research and Technical Blog

# Navigation Links
navbar-links:
  Home: "/"
  Resume: "/resume/"
  Research: "/research/"
  Blog: "/blog/"
  Conferences: "/conferences"

# Profile Image
avatar: "/assets/img/profile.JPG"

# Social Media Links
social-network-links:
  email: "abdullah.sahruri@gmail.com"
  github: abdullahsahruri
  linkedin: abdullahsahruri
  youtube: "@asahruri"

# Date Format
date_format: "%B %-d, %Y"

# Jekyll Configuration
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default Layout Settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "page"

# Exclude from processing
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - readme
  - screenshot.png
  - docs/
  - beautiful-jekyll-theme.gemspec
  - Appraisals
  - staticman.yml

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
